### ISSUE TITLE
[feat] Safe Ball Removal

### ISSUE THREAD

**Issue by lemonchu** [Yao-class-cpp-studio/GameX#81]
It is easy to add new ball by

`auto new_unit = world_->CreateUnit<Logic::Units::RegularBall>(new_player->PlayerId(), glm::vec3{0.0f, 1.0f, 0.0f}, 1.0f,1.0f);`

But, removing a ball is rather a difficult process since a `RegularBall` is associated with it corresponding `Actor`, `Object`.

How can we remove a ball safely?

**Comment by EnderXie23** [comment]
We may do this by recording the id of the ball and call world_->RemoveUnit(uint64_t unit_id).

**Comment by lemonchu** [comment]
> We may do this by recording the id of the ball and call world_->RemoveUnit(uint64_t unit_id).

It is an effective method! However, after calling the removal function, the physic ball involved in the calculation will be removed, but the image of the ball will be left on the board, which makes the board a little mess. 

Besides, removing a ball will lead to unexpected seg_fault when app quits. It looks more like a critical issue in src/GameX. 

Well, I am posting this issue because a multiplayer room must handle balls' quit. Such a headache, ahhhhhh!

**Comment by lemonchu** [comment]
This issue is ready to close. Actually we found a bug in actor removal in game_ball.cpp. 
Refer to [Original Code](https://github.com/Yao-class-cpp-studio/GameX/blob/7f7c214410175ce741f623fa7c44f69e9b47e115/src/GameBall/core/game_ball.cpp#L106C3-L127C42), and [Fixed Code](https://github.com/lemonchu/GameX/blob/5de80432d34993deb51358c2f7be1456ffa07b01/src/GameBall/core/game_ball.cpp#L466C1-L495C1)
